# -*- coding: utf-8 -*-
"""Untitled106.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dgw-P65y0wfdDrOjS-s3T8Wb-jLxOoGh
"""

!pip install -q streamlit groq pyngrok

import streamlit as st
from groq import Groq

# -----------------------------
# Groq API
# -----------------------------
client = Groq(
    api_key="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"
)

# -----------------------------
# Page Config
# -----------------------------
st.set_page_config(
    page_title="Groq AI Chatbot",
    page_icon="🤖",
    layout="wide"
)

# -----------------------------
# CSS
# -----------------------------
st.markdown("""
<style>

.stApp{
    background:#0f172a;
}

.user-box{
    background:#2563eb;
    color:white;
    padding:12px;
    border-radius:15px;
}

.bot-box{
    background:#1e293b;
    color:white;
    padding:12px;
    border-radius:15px;
}

</style>
""",unsafe_allow_html=True)

# -----------------------------
# Sidebar
# -----------------------------
with st.sidebar:

    st.title("⚙ Settings")

    model=st.selectbox(
        "Model",
        [
            "llama-3.3-70b-versatile",
            "llama3-70b-8192",
            "llama3-8b-8192"
        ]
    )

    temperature=st.slider(
        "Temperature",
        0.0,
        2.0,
        0.7
    )

    max_tokens=st.slider(
        "Max Tokens",
        100,
        4096,
        1024
    )

    if st.button("Clear Chat"):
        st.session_state.messages=[]
        st.rerun()

# -----------------------------
# Title
# -----------------------------
st.title("🤖 Groq AI Chatbot")

st.write("Powered by Groq")

# -----------------------------
# Chat History
# -----------------------------
if "messages" not in st.session_state:
    st.session_state.messages=[]

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# -----------------------------
# User Input
# -----------------------------
prompt=st.chat_input("Ask anything...")

if prompt:

    st.session_state.messages.append(
        {
            "role":"user",
            "content":prompt
        }
    )

    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):

        placeholder=st.empty()

        answer=""

        stream=client.chat.completions.create(

            model=model,

            messages=st.session_state.messages,

            temperature=temperature,

            max_completion_tokens=max_tokens,

            stream=True

        )

        for chunk in stream:

            if chunk.choices[0].delta.content:

                answer+=chunk.choices[0].delta.content

                placeholder.markdown(answer+"▌")

        placeholder.markdown(answer)

    st.session_state.messages.append(
        {
            "role":"assistant",
            "content":answer
        })

